repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: "v3.4.0"
      hooks:
          - id: check-merge-conflict
            stages: [ commit, push ]

          - id: check-ast
            stages: [ push ]

          - id: check-json
            stages: [ push ]

          - id: fix-encoding-pragma
            stages: [ push ]

    - repo: local
      hooks:
          - id: autoflake
            name: autoflake
            entry: poetry run autoflake --ignore-init-module-imports --remove-all-unused-imports --remove-unused-variables --expand-star-imports -i -r -v src
            language: system
            pass_filenames: false
            stages: [ commit, push ]

          - id: black
            name: black
            entry: poetry run black src
            language: system
            pass_filenames: false
            stages: [ commit, push ]

          - id: isort
            name: isort
            entry: poetry run isort src
            language: system
            pass_filenames: false
            stages: [ commit, push ]

          - id: mypy
            name: mypy check
            entry: poetry run mypy src
            language: system
            pass_filenames: false
            stages: [ commit, push ]

          - id: pytest
            name: pytest
            entry: poetry run pytest
            language: system
            pass_filenames: false
            stages: [ push ]

          - id: flake8
            name: flake8 check
            entry: poetry run flake8 src
            language: system
            pass_filenames: false
            stages: [ commit, push ]